version: '3'
services:
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example
  db-top-java:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - /Users/viktorma/mysql/top_java_data:/var/lib/postgresql/data/
